version: '3'

services:
  api: 
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - psql
    restart: always
    ports:
      - 3000:3000
    environment:
      - DSN=host=localhost user=ajk password=11012005 dbname=ajkdb port=5432 sslmode=disable
      - ADMIN_NAME=junaid
      - ADMIN_PASSWORD=111
      - USERNAME="junaidkaidakath@gmail.com"
      - PASSWORD="rkjsjsaqbxwuitvl"
      - HOST="smtp.gmail.com"
      - SECRET_KEY=randomcharactersandnums

  psql:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=ajk
      - POSTGRES_PASSWORD=11012005
      - POSTGRES_DB=ajkdb
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  data: